### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by KatiaSishost** [psychic-api/rag-stack#31]
No dependencies to install or update

Installing the current project: rag-stack (0.1.0)
llm/local/ggml-gpt4all-j-v1.3-groovy.bin already exists, skipping download.

🔮 Ragstack is almost ready.
Access the UI at http://localhost:5173 and send queries to http://localhost:8080/ask-question

Found model file at  /home/chatmyfiles/server/llm/local/ggml-gpt4all-j-v1.3-groovy.bin
Invalid model file
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/chatmyfiles/server/server/main.py", line 38, in <module>
    llm = get_selected_llm()
  File "/home/chatmyfiles/server/llm/llm.py", line 24, in get_selected_llm
    return Gpt4AllLLM()
  File "/home/chatmyfiles/server/llm/llm.py", line 40, in __init__
    self.llm = GPT4All(
  File "/root/.cache/pypoetry/virtualenvs/rag-stack-Radxutw4-py3.10/lib/python3.10/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Unable to instantiate model (type=value_error)
Stopping Docker containers...
qdrant
qdrant

**Comment by dominguesg** [comment]
Same problem here

**Comment by Siddhijain16** [comment]
I am also facing same problem, any solution for this ?

**Comment by TorecLuik** [comment]
Yes, (re)install Torch (see the torch web for the command for your gpu setup). 

But that doesn't solve all the other issues I ran into later as well =) goodluck

**Comment by Victorivus** [comment]
I finally fixed everything by fixing the gpt4all and the torch versions in the `server/pyproject.toml` to `gpt4all="1.0.0"` and `torch=">=2.0.0, !=2.0.1, !=2.1.0"` and rerunning in the server folder:

`poetry lock`
